### PR TITLE
Update MatrixUtil, EnumMap instead of HashMap, create FastQuadUploader

### PR DESCRIPTION
**Pull request by Meldexun**
_**Update MatrixUtil to 1.2.1:**_ Adds a few methods used by my other projects. Just want to make sure FBP doesn't crash with my mods.

_**Replace HashMap with EnumMap:**_ EnumMap is faster.

_**Create FastQuadUploader.java:**_ Works exactly the same as FastCubeUploader but instead just puts a south facing quad into the buffer.

### CODE REVIEW

**Comment by JustDesoroxxx** [comment]
> _**Create FastQuadUploader.java:**_ Works exactly the same as FastCubeUploader but instead just puts a south facing quad into the buffer.

So that is for rendering 2D textures instead of cubes right?

**Comment by Desoroxxx** [comment]
Could I have an anwser on this please @Meldexun

**Comment by Meldexun** [comment]
> So that is for rendering 2D textures instead of cubes right?

Yes

**Comment by Desoroxxx** [comment]
Could you add an example 2D Particle to go with it??

**Comment by Meldexun** [comment]
I added an example 2d spinning flame particle which implements the new IFBPParticle interface which was added to reduce duplicate render code.

Also MatrixUtil was updated to version 1.2.2.

**Comment by Desoroxxx** [comment]
Good will merge this weekend unless you want to change something.

**Pull request merged**
